name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-12-07
        components: rustfmt, clippy
        override: true
        
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Formatting Check
      run: cargo +nightly-2020-12-07 fmt -- --check

